DROP TABLE IF EXISTS `#__mobilenews`;

CREATE TABLE `#__mobilenews` (
	`id`       INT(100)     NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(100) NOT NULL,
	`text` VARCHAR(500) NOT NULL,
  `date` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `img` VARCHAR(100) NOT NULL,
	PRIMARY KEY (`id`)
)
	ENGINE =MyISAM
	AUTO_INCREMENT =0
	DEFAULT CHARSET =utf8;
